function create_layer_frequencies_files(dataInputFolder, writeHeader)
%CREATE_LAYER_FREQUENCIES_FILE Summary of this function goes here
%   Detailed explanation goes here

task = 6;    
[subjects, ~, ~, ~, ~,...
  ~, ~, ~, ~, layerSelectionData, ~,...
  ~, ~, ~] = aggregate_csv_task_data([dataInputFolder,...
    '\subject_data\allresponses_task_' num2str(task) '.csv'], task);
numLayers = size(layerSelectionData.subjectLayerSelectionsByStage, 3);

%Write layer frequencies aggregated over all trials for each subject
write_layer_frequencies_file(subjects, layerSelectionData.layers, layerSelectionData.permutations,...
    numLayers,...
    layerSelectionData.subjectLayerSelections, '', writeHeader);

%Write layer frequencies at each trial for each subject
write_layer_frequencies_by_trial_file(subjects, layerSelectionData.layers, layerSelectionData.permutations,...
    numLayers,...
    layerSelectionData.subjectLayerSelections, '', writeHeader);

end