%% SUBJECT TABLE DESIGN
% 
% Subject_number: subject number
% Phase_number: experiment phase
% Trial_number: trial number within phase 
% Query_type: 'Identify' or 'Locate'
% Layer_type: 'Simultaneous', 'Sequential', or 'User Choice'
% Phase_type = 1 for training phase, 2 for testing phase.
% 
% Presentation_order = Order of layers in sequential trials. 123 = ISM, 132 = IMS.
% User_choice = Number of layer chosen by user. When layer type was not 
%   'User Choice', will be 0. Otherwise, 1,2,3 for I,S,M.
% 
% Trial_time: time spent on trial by user, in ms. Subject numbers <= 6 lack
%   times in block 20, due to a GUI bug.
% Trial_score: This score should not be analyzed. This score was generated by the 
%   system after each trial. An average of these scores was presented to the 
%   subject at the end of each block.
% Specified_answer: the facility or sector specified in the exam, the idea 
%   being that all facilities are represented equally. The specified answer 
%   is not necessarily the same as the one given by the normative solution. 
%   Some non-specified answer may be more probable by random chance.
% 
% Normalization_compensation - Measures degree user relied on post-answer 
%   probability normalization for this trial. Computed as the sum of the absolute 
%   value of the difference between raw and normalized probabilities.
%
% --(The following three items are required to parse the trial probabilities)--
% Number_probability_sets: the number of probability sets reported in this trial. 
%   Can be 1, 2 or 3, depending on how many layer presentations occurred.
% Number_facilities: the number of facilities being tested in this trial.
%   At times during training, not all facilities have been learned, so not 
%   all will be tested. Currently 2-4.
% Max_probs_in_set: Currently always 4.
% 
% --(The following items are metrics comparing human to normative performance)--
% WTA = Winner-take-all distance (0 if normative and human same, 1 if different)
% TVDnh = Total variation distance (normative,human)
% TVDnr = Total variation distance (normative,random)
% KLDnh = KL divergence (normative,human)
% KLDnr = KL divergence (normative,random)
% KLDSnh = Symmetrized KL divergence (normative,human)
% KLDSnr = Symmetrized KL divergence (normative,random)
% RMSnh = RMS divergence (normative,human)
% RMSnr = RMS divergence (normative,random)
% 
% --(The remainder are probabilities)--
% They are arranged in blocks, with the block order being:
%   Probs_norm: normative solution probabilities
%   Probs_human: human (subject reported) probabilities
%   Probs_random: random (naive) model probabilities
%   Raw_probs_human: human (subject reported) probabilities prior to normalization step
% 
% Each block has 12 entries arranged into Number_probability_sets probability sets 
%   of Max_probs_in_set probabilities.
%   of which the first Number_facilities probabilities will be set.
% 
% When layertype = 'Simultaneous', Number_probability_sets = 1.
% When layertype = 'Sequential',   Number_probability_sets = 3, corresponding to: 
%   Set 1 = probabilities after 1st layer, 
%   Set 2 = probabilities after 2nd layer, 
%   Set 3 = probabilities after 3rd layer
% When layertype = 'User Choice',  Number_probability_sets will be 3, corresponding to:
%   Set 1 = answers when the layer shown is I.
%   Set 2 = answers when layers shown are IS (i.e. if user chooses SIGINT).
%   Set 3 = answers when layers shown are IM (i.e. if user chooses MASINT). 

subject_data_headings = [...
    'Subject_number' ...
    'Phase_number' 'Trial_number' 'Query_type' 'Layer_type' 'Phase_type' ...
    'Presentation_order' 'User_choice' 'Trial_time', 'Trial_score' 'Specified_answer' ...
    'Normalization_compensation', ...
    'Number_probability_sets' 'Number_facilities' 'Max_probs_in_set' ...
    'WTAnh' 'WTAnr' 'TVDnh' 'TVDnr' 'KLDnh' 'KLDnr' 'KLDSnh' 'KLDSnr' 'RMSnh' 'RMSnr' ...
    probs_headings('Probs_norm_1',4) probs_headings('Probs_norm_2',4) probs_headings('Probs_norm_3',4) ...
    probs_headings('Probs_human_1',4) probs_headings('Probs_human_2',4) probs_headings('Probs_human_3',4) ...
    probs_headings('Probs_random_1',4) probs_headings('Probs_random_2',4) probs_headings('Probs_random_3',4) ...
    probs_headings('Raw_probs_human_1',4) probs_headings('Raw_probs_human_2',4) probs_headings('Raw_probs_human_3',4) ...
    ];

[numbasefields, Subject_number_idx, ...
    Phase_number_idx, Trial_number_idx, Query_type_idx, Layer_type_idx, Phase_type_idx, ...
    Presentation_order_idx, User_choice_idx, Trial_time_idx, Trial_score_idx, Specified_answer_idx, ...
    Norm_comp_idx, ...
    Number_probability_sets_idx, Number_facilities_idx, Max_probs_in_set_idx, ...
    WTAnh_idx, WTAnr_idx, TVDnh_idx, TVDnr_idx, KLDnh_idx, KLDnr_idx  KLDSnh_idx KLDSnr_idx RMSnh_idx RMSnr_idx ...
    ] = enum;
normdataoffset =   numbasefields;
humandataoffset =  numbasefields +   max_probsets*max_probs_in_set;
randomdataoffset = numbasefields + 2*max_probsets*max_probs_in_set;
rawdataoffset =    numbasefields + 3*max_probsets*max_probs_in_set;
enddata =          numbasefields + 4*max_probsets*max_probs_in_set;
